openapi: 3.0.0
info:
  title: API de Usuarios y Objetivos
  version: 1.0.0
paths:
  /usuarios/:
    post:
      summary: Crea un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre_usuario:
                  type: string
                correo_electronico:
                  type: string
                contrasena:
                  type: string
      responses:
        '201':
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nombre_usuario:
                    type: string
                  correo_electronico:
                    type: string
                  contrasena:
                    type: string
                  fecha_registro:
                    type: string
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor
    get:
      summary: Obtiene todos los usuarios
      responses:
        '200':
          description: Lista de usuarios obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nombre_usuario:
                      type: string
                    correo_electronico:
                      type: string
                    contrasena:
                      type: string
                    fecha_registro:
                      type: string
        '500':
          description: Error interno del servidor
  /usuarios/{id}:
    get:
      summary: Obtiene un usuario por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Usuario obtenido exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nombre_usuario:
                    type: string
                  correo_electronico:
                    type: string
                  contrasena:
                    type: string
                  fecha_registro:
                    type: string
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
    put:
      summary: Actualiza un usuario por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre_usuario:
                  type: string
                correo_electronico:
                  type: string
                contrasena:
                  type: string
      responses:
        '200':
          description: Usuario actualizado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nombre_usuario:
                    type: string
                  correo_electronico:
                    type: string
                  contrasena:
                    type: string
                  fecha_registro:
                    type: string
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
    delete:
      summary: Elimina un usuario por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Usuario eliminado exitosamente
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
  /objetivos/:
    post:
      summary: Crea un nuevo objetivo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  description: Nombre del objetivo.
                descripcion:
                  type: string
                  description: Descripci贸n del objetivo.
                tipo_objetivo:
                  type: string
                  description: Tipo de objetivo (ej: "Salud", "Productividad").
                valor_cuantitativo:
                  type: number
                  description: Valor cuantitativo del objetivo.
                unidad_medida:
                  type: string
                  description: Unidad de medida del valor cuantitativo.
                fecha_inicio:
                  type: string
                  format: date
                  description: Fecha de inicio del objetivo (YYYY-MM-DD).
                fecha_fin:
                  type: string
                  format: date
                  description: Fecha de fin del objetivo (YYYY-MM-DD).
      responses:
        '201':
          description: Objetivo creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_objetivo:
                    type: integer
                    description: ID del objetivo.
                  nombre:
                    type: string
                    description: Nombre del objetivo.
                  descripcion:
                    type: string
                    description: Descripci贸n del objetivo.
                  tipo_objetivo:
                    type: string
                    description: Tipo de objetivo.
                  valor_cuantitativo:
                    type: number
                    description: Valor cuantitativo.
                  unidad_medida:
                    type: string
                    description: Unidad de medida.
                  fecha_inicio:
                    type: string
                    format: date
                    description: Fecha de inicio (YYYY-MM-DD).
                  fecha_fin:
                    type: string
                    format: date
                    description: Fecha de fin (YYYY-MM-DD).
        '400':
          description: Solicitud incorrecta
        '500':
          description: Error interno del servidor
    get:
      summary: Obtiene todos los objetivos
      responses:
        '200':
          description: Lista de objetivos obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id_objetivo:
                      type: integer
                      description: ID del objetivo.
                    nombre:
                      type: string
                      description: Nombre del objetivo.
                    descripcion:
                      type: string
                      description: Descripci贸n del objetivo.
                    tipo_objetivo:
                      type: string
                      description: Tipo de objetivo.
                    valor_cuantitativo:
                      type: number
                      description: Valor cuantitativo.
                    unidad_medida:
                      type: string
                      description: Unidad de medida.
                    fecha_inicio:
                      type: string
                      format: date
                      description: Fecha de inicio (YYYY-MM-DD).
                    fecha_fin:
                      type: string
                      format: date
                      description: Fecha de fin (YYYY-MM-DD).
        '500':
          description: Error interno del servidor
  /objetivos/{id}:
    get:
      summary: Obtiene un objetivo por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Objetivo obtenido exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_objetivo:
                    type: integer
                    description: ID del objetivo.
                  nombre:
                    type: string
                    description: Nombre del objetivo.
                  descripcion:
                    type: string
                    description: Descripci贸n del objetivo.
                  tipo_objetivo:
                    type: string
                    description: Tipo de objetivo.
                  valor_cuantitativo:
                    type: number
                    description: Valor cuantitativo.
                  unidad_medida:
                    type: string
                    description: Unidad de medida.
                  fecha_inicio:
                    type: string
                    format: date
                    description: Fecha de inicio (YYYY-MM-DD).
                  fecha_fin:
                    type: string
                    format: date
                    description: Fecha de fin (YYYY-MM-DD).
        '404':
          description: Objetivo no encontrado
        '500':
          description: Error interno del servidor
    put:
      summary: Actualiza un objetivo por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  description: Nombre del objetivo.
                descripcion:
                  type: string
                  description: Descripci贸n del objetivo.
                tipo_objetivo:
                  type: string
                  description: Tipo de objetivo.
                valor_cuantitativo:
                  type: number
                  description: Valor cuantitativo.
                unidad_medida:
                  type: string
                  description: Unidad de medida.
                fecha_inicio:
                  type: string
                  format: date
                  description: Fecha de inicio (YYYY-MM-DD).
                fecha_fin:
                  type: string
                  format: date
                  description: Fecha de fin (YYYY-MM-DD).
      responses:
        '200':
          description: Objetivo actualizado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_objetivo:
                    type: integer
                    description: ID del objetivo.
                  nombre:
                    type: string
                    description: Nombre del objetivo.
                  descripcion:
                    type: string
                    description: Descripci贸n del objetivo.
                  tipo_objetivo:
                    type: string
                    description: Tipo de objetivo.
                  valor_cuantitativo:
                    type: number
                    description: Valor cuantitativo.
                  unidad_medida:
                    type: string
                    description: Unidad de medida.
                  fecha_inicio:
                    type: string
                    format: date
                    description: Fecha de inicio (YYYY-MM-DD).
                  fecha_fin:
                    type: string
                    format: date
                    description: Fecha de fin (YYYY-MM-DD).
        '404':
          description: Objetivo no encontrado
        '500':
          description: Error interno del servidor
    delete:
      summary: Elimina un objetivo por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Objetivo eliminado exitosamente
        '404':
          description: Objetivo no encontrado
        '500':
          description: Error interno del servidor